// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// invSympdC
arma::mat invSympdC(arma::mat m);
RcppExport SEXP phylomice_invSympdC(SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type m(mSEXP);
    __result = Rcpp::wrap(invSympdC(m));
    return __result;
END_RCPP
}
// invC
arma::mat invC(arma::mat m);
RcppExport SEXP phylomice_invC(SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type m(mSEXP);
    __result = Rcpp::wrap(invC(m));
    return __result;
END_RCPP
}
// symC
arma::mat symC(arma::mat m);
RcppExport SEXP phylomice_symC(SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type m(mSEXP);
    __result = Rcpp::wrap(symC(m));
    return __result;
END_RCPP
}
