# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

invSympdC <- function(m) {
    .Call('phylomice_invSympdC', PACKAGE = 'phylomice', m)
}

invC <- function(m) {
    .Call('phylomice_invC', PACKAGE = 'phylomice', m)
}

symC <- function(m) {
    .Call('phylomice_symC', PACKAGE = 'phylomice', m)
}

